import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "@/components/banner/banner";
import Navbar from "@/components/navbar/navbar";
import CardCarousel from "@/components/card-carousel/card-carousel";
import {getPopularVideos, getVideos, getWatchItAgainVideos} from "@/lib/videos";
import getRedirectUser from "@/utils/redirectUser";

export async function getServerSideProps(context) {
    const {userId, token} = await getRedirectUser(context);

    const watchItAgainVideos = await getWatchItAgainVideos(userId, token);
    const disneyVideos = await getVideos('disney trailer');
    const productivityVideos = await getVideos('productivity');
    const travelVideos = await getVideos('travel');
    const popularVideos = await getPopularVideos();
    return {props: {disneyVideos, travelVideos, productivityVideos, popularVideos, watchItAgainVideos}};
}

export default function Home({disneyVideos, travelVideos, productivityVideos, popularVideos, watchItAgainVideos = []}) {
    return (
        <>
            <Head>
                <title>Fulopflix</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Navbar username='alexfulop@gmail.com'/>
                <Banner videoId='tcrNsIaQkb4'
                        title='Clifford the red dog'
                        subTitle='A very cute dog'
                        imgUrl='/static/evelynn.jpg'/>
                <div className={styles.sectionWrapper}>
                    <CardCarousel title='Disney' videos={disneyVideos} size='large'/>
                    <CardCarousel title='Watch it again' videos={watchItAgainVideos} size='small'/>
                    <CardCarousel title='Travel' videos={travelVideos} size='small'/>
                    <CardCarousel title='Productivity' videos={productivityVideos} size='medium'/>
                    <CardCarousel title='Popular' videos={popularVideos} size='small'/>
                </div>
            </main>
        </>
    )
}
